# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae9191f8eae303c3535972d45fad681258cbac625e08224fc1799629b5a7e44d25a0bbb6fb6b321f02bd31d0cae88773a72b46ffbfd6d9603672143aa39ca291

test:
  secret_key_base: cd4c73fface99b354cacf5fecd650c8f811720fbdbc8c2f91c6c0e1faec5235d8caca90f8be3896af3be1093f36eed7824b39f60a97cac3ee38d73836707570d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
